name = "Endless Swamp"
author = "To_Binio"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "22877e6a4d4fd8e300f3284ba16539b6b33d92584cfd921e28545eb410691ce0"

[versions]
fabric = "0.16.8"
minecraft = "1.21.1"
